In order to match county topojson we need an id in correct FIPS format just as it is in topojson: https://d3js.org/us-10m.v1.json


Explanation found here: https://groups.google.com/forum/#!topic/d3-js/RsHIi-CavO4
"
If you're referring to the provided us.json TopoJSON example file (as 
used in [1], for example), the id of each geometry is the 5-digit FIPS 
code: 

  http://www.itl.nist.gov/fipspubs/co-codes/states.txt 

The first two digits indicate the state code (d.id / 1000 | 0), and 
the last three digits (d.id % 1000) are the county code.
"

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('County_Zhvi_AllHomes.csv')

In [3]:
df

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,1996-04,1996-05,1996-06,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
0,3101,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,6,37,1,159400.0,159500.0,159200.0,...,549500.0,551600,554400,558100,561200,563700,565900,568200,571400,574400
1,139,Cook,IL,Chicago,17,31,2,128700.0,129000.0,128900.0,...,206700.0,209100,211200,211900,212200,212600,213100,214000,215100,215900
2,2402,Maricopa,AZ,Phoenix,4,13,3,107300.0,107400.0,107700.0,...,236600.0,237600,238400,239100,240000,241400,243300,244800,245900,246900
3,2841,San Diego,CA,San Diego,6,73,4,164700.0,164400.0,164000.0,...,528400.0,528300,528300,530700,535200,541200,545900,548500,551200,553900
4,1286,Orange,CA,Los Angeles-Long Beach-Anaheim,6,59,5,199900.0,199900.0,200400.0,...,672200.0,675000,676600,676200,676900,679600,681600,684000,687900,691600
5,581,Kings,NY,New York,36,47,6,NaN,NaN,NaN,...,684100.0,689600,692000,696000,704600,718300,730300,739400,746700,752500
6,2964,Miami-Dade,FL,Miami-Fort Lauderdale,12,86,7,96000.0,95700.0,95400.0,...,266100.0,267400,268200,268200,268000,268500,270000,272100,274600,276800
7,978,Dallas,TX,Dallas-Fort Worth,48,113,8,NaN,NaN,NaN,...,170700.0,171400,173000,174900,176100,176700,176800,176900,177700,178700
8,1347,Queens,NY,New York,36,81,9,NaN,NaN,NaN,...,478300.0,478900,484100,494100,504400,511700,517900,525600,537200,547300
9,2832,Riverside,CA,Riverside,6,65,10,124100.0,123500.0,122900.0,...,332800.0,333600,334700,335700,337100,339200,341800,344300,346400,347700
10,3250,San Bernardino,CA,Riverside,6,71,11,101700.0,101800.0,101800.0,...,299400.0,300800,301700,302800,304400,306500,309000,310900,312600,314400
11,445,Clark,NV,Las Vegas,32,3,12,124600.0,123900.0,123300.0,...,216300.0,217800,219000,220200,221900,224300,226800,229000,231400,233600
12,207,King,WA,Seattle,53,33,13,165200.0,165000.0,165100.0,...,528100.0,531600,535300,541700,552300,565900,576800,581300,585100,589700
13,791,Wayne,MI,Detroit,26,163,14,NaN,92300.0,92900.0,...,68400.0,69300,70300,71400,72400,73100,73200,73500,75500,78000
14,2049,Tarrant,TX,Dallas-Fort Worth,48,439,15,NaN,NaN,NaN,...,177400.0,178200,180100,182100,183500,185100,186500,187500,188600,189900
15,3136,Santa Clara,CA,San Jose,6,85,16,254400.0,254100.0,253900.0,...,989400.0,998300,1007800,1017200,1027500,1036100,1043500,1051700,1060800,1068000
16,1561,Broward,FL,Miami-Fort Lauderdale,12,11,17,86100.0,86200.0,86100.0,...,222300.0,223400,224400,225900,227900,230400,231900,233000,234900,236800
17,2452,New York,NY,New York,36,61,18,NaN,NaN,330800.0,...,1177600.0,1182400,1190600,1198200,1219500,1259800,1324200,1395200,1440200,1450300
18,3175,Philadelphia,PA,Philadelphia,42,101,19,50000.0,49900.0,49600.0,...,132600.0,133600,134500,135200,135600,136500,137000,137700,138900,140200
19,1510,Alameda,CA,San Francisco,6,1,20,190600.0,190300.0,189900.0,...,751800.0,758000,766200,772200,774100,774700,776500,778700,781300,783800
20,2801,Middlesex,MA,Boston,25,17,21,173000.0,173200.0,173000.0,...,476700.0,479400,482800,486200,489500,492900,496100,498900,500800,501500
21,2046,Suffolk,NY,New York,36,103,22,NaN,NaN,NaN,...,362500.0,365700,369700,375800,383300,386700,386400,386200,386200,385100
22,3017,Sacramento,CA,Sacramento,6,67,23,120900.0,120900.0,121000.0,...,319200.0,320700,322300,325100,327900,330200,332800,334900,336900,338700
23,1252,Nassau,NY,New York,36,59,24,186700.0,186900.0,186900.0,...,485500.0,488900,492500,495500,499200,503600,507000,507200,507300,508200
24,2993,Palm Beach,FL,Miami-Fort Lauderdale,12,99,25,98100.0,98200.0,98400.0,...,248800.0,249900,250500,251300,252200,253000,253400,254300,255700,256800
25,2241,Cuyahoga,OH,Cleveland,39,35,26,93700.0,94000.0,94500.0,...,112700.0,113800,114400,114700,115300,116500,117300,117900,118900,119900
26,3165,Hillsborough,FL,Tampa,12,57,27,74200.0,74100.0,73800.0,...,188500.0,190500,192500,193700,194100,194300,195200,196000,197100,198200
27,2614,Allegheny,PA,Pittsburgh,42,3,28,69300.0,69600.0,69700.0,...,135900.0,136500,137300,137800,138200,138700,139200,139800,140700,141600
28,1950,Oakland,MI,Detroit,26,125,29,139100.0,139800.0,140400.0,...,214900.0,216900,218700,220000,220800,222000,223100,223800,224800,225900
29,2288,Franklin,OH,Columbus,39,49,30,97300.0,97200.0,97300.0,...,147700.0,149200,150200,150800,151300,152000,152700,153200,154300,155500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,3096,Hot Springs,WY,NaN,56,17,1677,NaN,NaN,NaN,...,196400.0,196700,196700,196700,197100,197900,198500,198500,198600,198700
1677,2711,Guadalupe,NM,NaN,35,19,1678,NaN,NaN,NaN,...,132600.0,133900,134900,135800,136700,137600,138500,139000,138900,138700
1678,634,Meade,KS,NaN,20,119,1679,NaN,NaN,NaN,...,67400.0,67600,67900,68200,68400,68900,69400,69700,70000,70100
1679,539,Grant,OK,NaN,40,53,1680,29600.0,30400.0,31100.0,...,89200.0,91300,93300,95600,97800,99900,101000,101800,102500,103300
1680,2555,Stafford,KS,NaN,20,185,1681,NaN,NaN,NaN,...,57400.0,57600,57800,58000,58200,58600,58900,59200,59400,59500
1681,665,Ouray,CO,NaN,8,91,1682,101100.0,97200.0,94100.0,...,358200.0,361400,364500,367100,373000,379200,380500,379500,381100,383100
1682,1320,Pierce,ND,NaN,38,69,1683,NaN,NaN,NaN,...,135700.0,135700,135300,135000,134900,135000,135000,134700,134200,134000
1683,1282,Oneida,ID,NaN,16,71,1684,NaN,NaN,NaN,...,180500.0,182200,183100,184100,185600,187700,190200,192700,195400,197000
1684,1764,Haskell,KS,NaN,20,81,1685,NaN,NaN,NaN,...,96100.0,96500,96900,97300,97800,98400,98900,99200,99600,100000
1685,2497,Red Lake,MN,NaN,27,125,1686,NaN,NaN,NaN,...,103400.0,101800,100300,99000,97600,96900,96800,96500,96600,96900
1686,1130,Kearny,KS,Garden City,20,93,1687,NaN,NaN,NaN,...,92600.0,93000,93300,93700,94300,94900,95400,95800,96000,96100
1687,355,Adams,ID,NaN,16,3,1688,NaN,NaN,NaN,...,203000.0,202500,201700,201700,202500,203400,204700,206600,208800,210300
1688,1956,Osborne,KS,NaN,20,141,1689,NaN,NaN,NaN,...,59500.0,60000,60300,60500,60700,61100,61400,61700,61900,62000
1689,722,Smith,KS,NaN,20,183,1690,NaN,NaN,NaN,...,60700.0,61100,61400,61700,62000,62200,62600,62900,63200,63400
1690,596,Lewis,ID,NaN,16,61,1691,145400.0,145400.0,145400.0,...,164000.0,165600,166300,167200,168600,170300,172600,175100,177400,178900
1691,2899,Chautauqua,KS,NaN,20,19,1692,NaN,NaN,NaN,...,49000.0,49400,49400,49400,49800,50300,50500,50600,50900,51000
1692,3143,Sweet Grass,MT,NaN,30,97,1693,191900.0,191900.0,191900.0,...,206500.0,208000,209200,210300,211700,213300,214700,215600,216300,216900
1693,1005,Emmons,ND,NaN,38,29,1694,132900.0,132900.0,132900.0,...,138700.0,138700,138300,137900,138000,138000,137900,137600,137300,137000
1694,2103,Woodson,KS,NaN,20,207,1695,NaN,NaN,NaN,...,57500.0,57800,58000,58200,58500,58800,59100,59400,59600,59600
1695,311,Rush,KS,NaN,20,165,1696,NaN,NaN,NaN,...,59800.0,60100,60400,60700,61000,61200,61700,61900,62200,62400
1696,1867,Lincoln,KS,NaN,20,105,1697,NaN,NaN,NaN,...,62100.0,62500,62800,62900,63300,63800,64100,64400,64600,64600
1697,1125,Jewell,KS,NaN,20,89,1698,NaN,NaN,NaN,...,58900.0,59200,59300,59400,59800,60200,60500,60700,61000,61100
1698,1687,Edwards,KS,NaN,20,47,1699,NaN,NaN,NaN,...,54500.0,54800,55000,55200,55500,55700,56100,56400,56600,56600
1699,1665,Decatur,KS,NaN,20,39,1700,NaN,NaN,NaN,...,64000.0,64400,64500,64800,65200,65500,65800,66200,66400,66600
1700,2197,Cheyenne,KS,NaN,20,23,1701,NaN,NaN,NaN,...,68500.0,69000,69300,69400,69800,70300,70700,70900,71200,71400
1701,359,Adams,ND,NaN,38,1,1702,NaN,NaN,NaN,...,86300.0,86300,86200,86000,86000,85900,85800,85700,85600,85500
1702,305,Rich,UT,NaN,49,33,1703,NaN,NaN,NaN,...,456800.0,461500,464100,466500,470500,475400,480200,484300,488700,491500
1703,442,Clark,KS,NaN,20,25,1704,NaN,NaN,NaN,...,63400.0,63600,63900,64200,64500,64800,65200,65400,65700,66000
1704,2220,Comanche,KS,NaN,20,33,1705,NaN,NaN,NaN,...,55000.0,55400,55500,55700,56000,56300,56600,56900,57100,57000
1705,828,Alpine,CA,NaN,6,3,1706,NaN,NaN,NaN,...,280200.0,283400,285100,284400,282300,282900,278300,266200,258400,256900

In [5]:
def create_FIPS_id(row):
    stateCodeFIPS = row['StateCodeFIPS']
    countyCodeFIPS = row['MunicipalCodeFIPS']
    
    idFIPS = str(stateCodeFIPS).zfill(2) + str(countyCodeFIPS).zfill(3)
    
    return idFIPS

In [6]:
df['CountyCodeFIPS'] = df.apply(create_FIPS_id, axis=1)

In [19]:
dfDataColumns = set(list(df.columns)) - set(['RegionID', 'RegionName', 'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', 'SizeRank', 'CountyCodeFIPS'])
dfDataColumns = list(dfDataColumns)
dfDataColumns.sort()
dfDataColumns

['1996-04',
 '1996-05',
 '1996-06',
 '1996-07',
 '1996-08',
 '1996-09',
 '1996-10',
 '1996-11',
 '1996-12',
 '1997-01',
 '1997-02',
 '1997-03',
 '1997-04',
 '1997-05',
 '1997-06',
 '1997-07',
 '1997-08',
 '1997-09',
 '1997-10',
 '1997-11',
 '1997-12',
 '1998-01',
 '1998-02',
 '1998-03',
 '1998-04',
 '1998-05',
 '1998-06',
 '1998-07',
 '1998-08',
 '1998-09',
 '1998-10',
 '1998-11',
 '1998-12',
 '1999-01',
 '1999-02',
 '1999-03',
 '1999-04',
 '1999-05',
 '1999-06',
 '1999-07',
 '1999-08',
 '1999-09',
 '1999-10',
 '1999-11',
 '1999-12',
 '2000-01',
 '2000-02',
 '2000-03',
 '2000-04',
 '2000-05',
 '2000-06',
 '2000-07',
 '2000-08',
 '2000-09',
 '2000-10',
 '2000-11',
 '2000-12',
 '2001-01',
 '2001-02',
 '2001-03',
 '2001-04',
 '2001-05',
 '2001-06',
 '2001-07',
 '2001-08',
 '2001-09',
 '2001-10',
 '2001-11',
 '2001-12',
 '2002-01',
 '2002-02',
 '2002-03',
 '2002-04',
 '2002-05',
 '2002-06',
 '2002-07',
 '2002-08',
 '2002-09',
 '2002-10',
 '2002-11',
 '2002-12',
 '2003-01',
 '2003-02',
 '2003-03',
 '2003-04',
 '2003-05',
 '2003-06',
 '2003-07',
 '2003-08',
 '2003-09',
 '2003-10',
 '2003-11',
 '2003-12',
 '2004-01',
 '2004-02',
 '2004-03',
 '2004-04',
 '2004-05',
 '2004-06',
 '2004-07',
 '2004-08',
 '2004-09',
 '2004-10',
 '2004-11',
 '2004-12',
 '2005-01',
 '2005-02',
 '2005-03',
 '2005-04',
 '2005-05',
 '2005-06',
 '2005-07',
 '2005-08',
 '2005-09',
 '2005-10',
 '2005-11',
 '2005-12',
 '2006-01',
 '2006-02',
 '2006-03',
 '2006-04',
 '2006-05',
 '2006-06',
 '2006-07',
 '2006-08',
 '2006-09',
 '2006-10',
 '2006-11',
 '2006-12',
 '2007-01',
 '2007-02',
 '2007-03',
 '2007-04',
 '2007-05',
 '2007-06',
 '2007-07',
 '2007-08',
 '2007-09',
 '2007-10',
 '2007-11',
 '2007-12',
 '2008-01',
 '2008-02',
 '2008-03',
 '2008-04',
 '2008-05',
 '2008-06',
 '2008-07',
 '2008-08',
 '2008-09',
 '2008-10',
 '2008-11',
 '2008-12',
 '2009-01',
 '2009-02',
 '2009-03',
 '2009-04',
 '2009-05',
 '2009-06',
 '2009-07',
 '2009-08',
 '2009-09',
 '2009-10',
 '2009-11',
 '2009-12',
 '2010-01',
 '2010-02',
 '2010-03',
 '2010-04',
 '2010-05',
 '2010-06',
 '2010-07',
 '2010-08',
 '2010-09',
 '2010-10',
 '2010-11',
 '2010-12',
 '2011-01',
 '2011-02',
 '2011-03',
 '2011-04',
 '2011-05',
 '2011-06',
 '2011-07',
 '2011-08',
 '2011-09',
 '2011-10',
 '2011-11',
 '2011-12',
 '2012-01',
 '2012-02',
 '2012-03',
 '2012-04',
 '2012-05',
 '2012-06',
 '2012-07',
 '2012-08',
 '2012-09',
 '2012-10',
 '2012-11',
 '2012-12',
 '2013-01',
 '2013-02',
 '2013-03',
 '2013-04',
 '2013-05',
 '2013-06',
 '2013-07',
 '2013-08',
 '2013-09',
 '2013-10',
 '2013-11',
 '2013-12',
 '2014-01',
 '2014-02',
 '2014-03',
 '2014-04',
 '2014-05',
 '2014-06',
 '2014-07',
 '2014-08',
 '2014-09',
 '2014-10',
 '2014-11',
 '2014-12',
 '2015-01',
 '2015-02',
 '2015-03',
 '2015-04',
 '2015-05',
 '2015-06',
 '2015-07',
 '2015-08',
 '2015-09',
 '2015-10',
 '2015-11',
 '2015-12',
 '2016-01',
 '2016-02',
 '2016-03',
 '2016-04',
 '2016-05',
 '2016-06',
 '2016-07',
 '2016-08',
 '2016-09',
 '2016-10',
 '2016-11',
 '2016-12',
 '2017-01',
 '2017-02',
 '2017-03',
 '2017-04',
 '2017-05',
 '2017-06',
 '2017-07',
 '2017-08',
 '2017-09']

In [20]:
dfRelevantColumns = ['CountyCodeFIPS', 'RegionName', 'State', 'Metro', 'SizeRank'] + dfDataColumns

In [21]:
dfRelevantColumns

['CountyCodeFIPS',
 'RegionName',
 'State',
 'Metro',
 'SizeRank',
 '1996-04',
 '1996-05',
 '1996-06',
 '1996-07',
 '1996-08',
 '1996-09',
 '1996-10',
 '1996-11',
 '1996-12',
 '1997-01',
 '1997-02',
 '1997-03',
 '1997-04',
 '1997-05',
 '1997-06',
 '1997-07',
 '1997-08',
 '1997-09',
 '1997-10',
 '1997-11',
 '1997-12',
 '1998-01',
 '1998-02',
 '1998-03',
 '1998-04',
 '1998-05',
 '1998-06',
 '1998-07',
 '1998-08',
 '1998-09',
 '1998-10',
 '1998-11',
 '1998-12',
 '1999-01',
 '1999-02',
 '1999-03',
 '1999-04',
 '1999-05',
 '1999-06',
 '1999-07',
 '1999-08',
 '1999-09',
 '1999-10',
 '1999-11',
 '1999-12',
 '2000-01',
 '2000-02',
 '2000-03',
 '2000-04',
 '2000-05',
 '2000-06',
 '2000-07',
 '2000-08',
 '2000-09',
 '2000-10',
 '2000-11',
 '2000-12',
 '2001-01',
 '2001-02',
 '2001-03',
 '2001-04',
 '2001-05',
 '2001-06',
 '2001-07',
 '2001-08',
 '2001-09',
 '2001-10',
 '2001-11',
 '2001-12',
 '2002-01',
 '2002-02',
 '2002-03',
 '2002-04',
 '2002-05',
 '2002-06',
 '2002-07',
 '2002-08',
 '2002-09',
 '2002-10',
 '2002-11',
 '2002-12',
 '2003-01',
 '2003-02',
 '2003-03',
 '2003-04',
 '2003-05',
 '2003-06',
 '2003-07',
 '2003-08',
 '2003-09',
 '2003-10',
 '2003-11',
 '2003-12',
 '2004-01',
 '2004-02',
 '2004-03',
 '2004-04',
 '2004-05',
 '2004-06',
 '2004-07',
 '2004-08',
 '2004-09',
 '2004-10',
 '2004-11',
 '2004-12',
 '2005-01',
 '2005-02',
 '2005-03',
 '2005-04',
 '2005-05',
 '2005-06',
 '2005-07',
 '2005-08',
 '2005-09',
 '2005-10',
 '2005-11',
 '2005-12',
 '2006-01',
 '2006-02',
 '2006-03',
 '2006-04',
 '2006-05',
 '2006-06',
 '2006-07',
 '2006-08',
 '2006-09',
 '2006-10',
 '2006-11',
 '2006-12',
 '2007-01',
 '2007-02',
 '2007-03',
 '2007-04',
 '2007-05',
 '2007-06',
 '2007-07',
 '2007-08',
 '2007-09',
 '2007-10',
 '2007-11',
 '2007-12',
 '2008-01',
 '2008-02',
 '2008-03',
 '2008-04',
 '2008-05',
 '2008-06',
 '2008-07',
 '2008-08',
 '2008-09',
 '2008-10',
 '2008-11',
 '2008-12',
 '2009-01',
 '2009-02',
 '2009-03',
 '2009-04',
 '2009-05',
 '2009-06',
 '2009-07',
 '2009-08',
 '2009-09',
 '2009-10',
 '2009-11',
 '2009-12',
 '2010-01',
 '2010-02',
 '2010-03',
 '2010-04',
 '2010-05',
 '2010-06',
 '2010-07',
 '2010-08',
 '2010-09',
 '2010-10',
 '2010-11',
 '2010-12',
 '2011-01',
 '2011-02',
 '2011-03',
 '2011-04',
 '2011-05',
 '2011-06',
 '2011-07',
 '2011-08',
 '2011-09',
 '2011-10',
 '2011-11',
 '2011-12',
 '2012-01',
 '2012-02',
 '2012-03',
 '2012-04',
 '2012-05',
 '2012-06',
 '2012-07',
 '2012-08',
 '2012-09',
 '2012-10',
 '2012-11',
 '2012-12',
 '2013-01',
 '2013-02',
 '2013-03',
 '2013-04',
 '2013-05',
 '2013-06',
 '2013-07',
 '2013-08',
 '2013-09',
 '2013-10',
 '2013-11',
 '2013-12',
 '2014-01',
 '2014-02',
 '2014-03',
 '2014-04',
 '2014-05',
 '2014-06',
 '2014-07',
 '2014-08',
 '2014-09',
 '2014-10',
 '2014-11',
 '2014-12',
 '2015-01',
 '2015-02',
 '2015-03',
 '2015-04',
 '2015-05',
 '2015-06',
 '2015-07',
 '2015-08',
 '2015-09',
 '2015-10',
 '2015-11',
 '2015-12',
 '2016-01',
 '2016-02',
 '2016-03',
 '2016-04',
 '2016-05',
 '2016-06',
 '2016-07',
 '2016-08',
 '2016-09',
 '2016-10',
 '2016-11',
 '2016-12',
 '2017-01',
 '2017-02',
 '2017-03',
 '2017-04',
 '2017-05',
 '2017-06',
 '2017-07',
 '2017-08',
 '2017-09']

In [26]:
newDf = df[dfRelevantColumns]
newDf

,CountyCodeFIPS,RegionName,State,Metro,SizeRank,1996-04,1996-05,1996-06,1996-07,1996-08,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
0,06037,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,1,159400.0,159500.0,159200.0,158900.0,158700.0,...,549500.0,551600,554400,558100,561200,563700,565900,568200,571400,574400
1,17031,Cook,IL,Chicago,2,128700.0,129000.0,128900.0,128600.0,128400.0,...,206700.0,209100,211200,211900,212200,212600,213100,214000,215100,215900
2,04013,Maricopa,AZ,Phoenix,3,107300.0,107400.0,107700.0,108200.0,108600.0,...,236600.0,237600,238400,239100,240000,241400,243300,244800,245900,246900
3,06073,San Diego,CA,San Diego,4,164700.0,164400.0,164000.0,163700.0,163200.0,...,528400.0,528300,528300,530700,535200,541200,545900,548500,551200,553900
4,06059,Orange,CA,Los Angeles-Long Beach-Anaheim,5,199900.0,199900.0,200400.0,201000.0,202200.0,...,672200.0,675000,676600,676200,676900,679600,681600,684000,687900,691600
5,36047,Kings,NY,New York,6,NaN,NaN,NaN,NaN,NaN,...,684100.0,689600,692000,696000,704600,718300,730300,739400,746700,752500
6,12086,Miami-Dade,FL,Miami-Fort Lauderdale,7,96000.0,95700.0,95400.0,95400.0,95500.0,...,266100.0,267400,268200,268200,268000,268500,270000,272100,274600,276800
7,48113,Dallas,TX,Dallas-Fort Worth,8,NaN,NaN,NaN,NaN,NaN,...,170700.0,171400,173000,174900,176100,176700,176800,176900,177700,178700
8,36081,Queens,NY,New York,9,NaN,NaN,NaN,NaN,NaN,...,478300.0,478900,484100,494100,504400,511700,517900,525600,537200,547300
9,06065,Riverside,CA,Riverside,10,124100.0,123500.0,122900.0,122500.0,122000.0,...,332800.0,333600,334700,335700,337100,339200,341800,344300,346400,347700
10,06071,San Bernardino,CA,Riverside,11,101700.0,101800.0,101800.0,101800.0,102200.0,...,299400.0,300800,301700,302800,304400,306500,309000,310900,312600,314400
11,32003,Clark,NV,Las Vegas,12,124600.0,123900.0,123300.0,122900.0,122600.0,...,216300.0,217800,219000,220200,221900,224300,226800,229000,231400,233600
12,53033,King,WA,Seattle,13,165200.0,165000.0,165100.0,165300.0,165400.0,...,528100.0,531600,535300,541700,552300,565900,576800,581300,585100,589700
13,26163,Wayne,MI,Detroit,14,NaN,92300.0,92900.0,93700.0,90900.0,...,68400.0,69300,70300,71400,72400,73100,73200,73500,75500,78000
14,48439,Tarrant,TX,Dallas-Fort Worth,15,NaN,NaN,NaN,NaN,NaN,...,177400.0,178200,180100,182100,183500,185100,186500,187500,188600,189900
15,06085,Santa Clara,CA,San Jose,16,254400.0,254100.0,253900.0,254200.0,254800.0,...,989400.0,998300,1007800,1017200,1027500,1036100,1043500,1051700,1060800,1068000
16,12011,Broward,FL,Miami-Fort Lauderdale,17,86100.0,86200.0,86100.0,85700.0,85500.0,...,222300.0,223400,224400,225900,227900,230400,231900,233000,234900,236800
17,36061,New York,NY,New York,18,NaN,NaN,330800.0,375800.0,445200.0,...,1177600.0,1182400,1190600,1198200,1219500,1259800,1324200,1395200,1440200,1450300
18,42101,Philadelphia,PA,Philadelphia,19,50000.0,49900.0,49600.0,49400.0,49400.0,...,132600.0,133600,134500,135200,135600,136500,137000,137700,138900,140200
19,06001,Alameda,CA,San Francisco,20,190600.0,190300.0,189900.0,189800.0,190000.0,...,751800.0,758000,766200,772200,774100,774700,776500,778700,781300,783800
20,25017,Middlesex,MA,Boston,21,173000.0,173200.0,173000.0,172900.0,173200.0,...,476700.0,479400,482800,486200,489500,492900,496100,498900,500800,501500
21,36103,Suffolk,NY,New York,22,NaN,NaN,NaN,NaN,NaN,...,362500.0,365700,369700,375800,383300,386700,386400,386200,386200,385100
22,06067,Sacramento,CA,Sacramento,23,120900.0,120900.0,121000.0,121000.0,120700.0,...,319200.0,320700,322300,325100,327900,330200,332800,334900,336900,338700
23,36059,Nassau,NY,New York,24,186700.0,186900.0,186900.0,187000.0,186900.0,...,485500.0,488900,492500,495500,499200,503600,507000,507200,507300,508200
24,12099,Palm Beach,FL,Miami-Fort Lauderdale,25,98100.0,98200.0,98400.0,98500.0,98800.0,...,248800.0,249900,250500,251300,252200,253000,253400,254300,255700,256800
25,39035,Cuyahoga,OH,Cleveland,26,93700.0,94000.0,94500.0,95100.0,95600.0,...,112700.0,113800,114400,114700,115300,116500,117300,117900,118900,119900
26,12057,Hillsborough,FL,Tampa,27,74200.0,74100.0,73800.0,73400.0,72800.0,...,188500.0,190500,192500,193700,194100,194300,195200,196000,197100,198200
27,42003,Allegheny,PA,Pittsburgh,28,69300.0,69600.0,69700.0,70000.0,70300.0,...,135900.0,136500,137300,137800,138200,138700,139200,139800,140700,141600
28,26125,Oakland,MI,Detroit,29,139100.0,139800.0,140400.0,140900.0,141800.0,...,214900.0,216900,218700,220000,220800,222000,223100,223800,224800,225900
29,39049,Franklin,OH,Columbus,30,97300.0,97200.0,97300.0,97500.0,97600.0,...,147700.0,149200,150200,150800,151300,152000,152700,153200,154300,155500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,56017,Hot Springs,WY,NaN,1677,NaN,NaN,NaN,NaN,NaN,...,196400.0,196700,196700,196700,197100,197900,198500,198500,198600,198700
1677,35019,Guadalupe,NM,NaN,1678,NaN,NaN,NaN,NaN,NaN,...,132600.0,133900,134900,135800,136700,137600,138500,139000,138900,138700
1678,20119,Meade,KS,NaN,1679,NaN,NaN,NaN,NaN,NaN,...,67400.0,67600,67900,68200,68400,68900,69400,69700,70000,70100
1679,40053,Grant,OK,NaN,1680,29600.0,30400.0,31100.0,31600.0,32200.0,...,89200.0,91300,93300,95600,97800,99900,101000,101800,102500,103300
1680,20185,Stafford,KS,NaN,1681,NaN,NaN,NaN,NaN,NaN,...,57400.0,57600,57800,58000,58200,58600,58900,59200,59400,59500
1681,08091,Ouray,CO,NaN,1682,101100.0,97200.0,94100.0,91800.0,89200.0,...,358200.0,361400,364500,367100,373000,379200,380500,379500,381100,383100
1682,38069,Pierce,ND,NaN,1683,NaN,NaN,NaN,NaN,NaN,...,135700.0,135700,135300,135000,134900,135000,135000,134700,134200,134000
1683,16071,Oneida,ID,NaN,1684,NaN,NaN,NaN,NaN,NaN,...,180500.0,182200,183100,184100,185600,187700,190200,192700,195400,197000
1684,20081,Haskell,KS,NaN,1685,NaN,NaN,NaN,NaN,NaN,...,96100.0,96500,96900,97300,97800,98400,98900,99200,99600,100000
1685,27125,Red Lake,MN,NaN,1686,NaN,NaN,NaN,NaN,NaN,...,103400.0,101800,100300,99000,97600,96900,96800,96500,96600,96900
1686,20093,Kearny,KS,Garden City,1687,NaN,NaN,NaN,NaN,NaN,...,92600.0,93000,93300,93700,94300,94900,95400,95800,96000,96100
1687,16003,Adams,ID,NaN,1688,NaN,NaN,NaN,NaN,NaN,...,203000.0,202500,201700,201700,202500,203400,204700,206600,208800,210300
1688,20141,Osborne,KS,NaN,1689,NaN,NaN,NaN,NaN,NaN,...,59500.0,60000,60300,60500,60700,61100,61400,61700,61900,62000
1689,20183,Smith,KS,NaN,1690,NaN,NaN,NaN,NaN,NaN,...,60700.0,61100,61400,61700,62000,62200,62600,62900,63200,63400
1690,16061,Lewis,ID,NaN,1691,145400.0,145400.0,145400.0,145500.0,145500.0,...,164000.0,165600,166300,167200,168600,170300,172600,175100,177400,178900
1691,20019,Chautauqua,KS,NaN,1692,NaN,NaN,NaN,NaN,NaN,...,49000.0,49400,49400,49400,49800,50300,50500,50600,50900,51000
1692,30097,Sweet Grass,MT,NaN,1693,191900.0,191900.0,191900.0,192000.0,192000.0,...,206500.0,208000,209200,210300,211700,213300,214700,215600,216300,216900
1693,38029,Emmons,ND,NaN,1694,132900.0,132900.0,132900.0,133000.0,133000.0,...,138700.0,138700,138300,137900,138000,138000,137900,137600,137300,137000
1694,20207,Woodson,KS,NaN,1695,NaN,NaN,NaN,NaN,NaN,...,57500.0,57800,58000,58200,58500,58800,59100,59400,59600,59600
1695,20165,Rush,KS,NaN,1696,NaN,NaN,NaN,NaN,NaN,...,59800.0,60100,60400,60700,61000,61200,61700,61900,62200,62400
1696,20105,Lincoln,KS,NaN,1697,NaN,NaN,NaN,NaN,NaN,...,62100.0,62500,62800,62900,63300,63800,64100,64400,64600,64600
1697,20089,Jewell,KS,NaN,1698,NaN,NaN,NaN,NaN,NaN,...,58900.0,59200,59300,59400,59800,60200,60500,60700,61000,61100
1698,20047,Edwards,KS,NaN,1699,NaN,NaN,NaN,NaN,NaN,...,54500.0,54800,55000,55200,55500,55700,56100,56400,56600,56600
1699,20039,Decatur,KS,NaN,1700,NaN,NaN,NaN,NaN,NaN,...,64000.0,64400,64500,64800,65200,65500,65800,66200,66400,66600
1700,20023,Cheyenne,KS,NaN,1701,NaN,NaN,NaN,NaN,NaN,...,68500.0,69000,69300,69400,69800,70300,70700,70900,71200,71400
1701,38001,Adams,ND,NaN,1702,NaN,NaN,NaN,NaN,NaN,...,86300.0,86300,86200,86000,86000,85900,85800,85700,85600,85500
1702,49033,Rich,UT,NaN,1703,NaN,NaN,NaN,NaN,NaN,...,456800.0,461500,464100,466500,470500,475400,480200,484300,488700,491500
1703,20025,Clark,KS,NaN,1704,NaN,NaN,NaN,NaN,NaN,...,63400.0,63600,63900,64200,64500,64800,65200,65400,65700,66000
1704,20033,Comanche,KS,NaN,1705,NaN,NaN,NaN,NaN,NaN,...,55000.0,55400,55500,55700,56000,56300,56600,56900,57100,57000
1705,06003,Alpine,CA,NaN,1706,NaN,NaN,NaN,NaN,NaN,...,280200.0,283400,285100,284400,282300,282900,278300,266200,258400,256900

In [27]:
newDf.update(newDf[dfDataColumns].fillna(0))

/Users/mateusz/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py:3765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  raise_on_error=True)

In [28]:
newDf

,CountyCodeFIPS,RegionName,State,Metro,SizeRank,1996-04,1996-05,1996-06,1996-07,1996-08,...,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09
0,06037,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,1,159400.0,159500.0,159200.0,158900.0,158700.0,...,549500.0,551600,554400,558100,561200,563700,565900,568200,571400,574400
1,17031,Cook,IL,Chicago,2,128700.0,129000.0,128900.0,128600.0,128400.0,...,206700.0,209100,211200,211900,212200,212600,213100,214000,215100,215900
2,04013,Maricopa,AZ,Phoenix,3,107300.0,107400.0,107700.0,108200.0,108600.0,...,236600.0,237600,238400,239100,240000,241400,243300,244800,245900,246900
3,06073,San Diego,CA,San Diego,4,164700.0,164400.0,164000.0,163700.0,163200.0,...,528400.0,528300,528300,530700,535200,541200,545900,548500,551200,553900
4,06059,Orange,CA,Los Angeles-Long Beach-Anaheim,5,199900.0,199900.0,200400.0,201000.0,202200.0,...,672200.0,675000,676600,676200,676900,679600,681600,684000,687900,691600
5,36047,Kings,NY,New York,6,0.0,0.0,0.0,0.0,0.0,...,684100.0,689600,692000,696000,704600,718300,730300,739400,746700,752500
6,12086,Miami-Dade,FL,Miami-Fort Lauderdale,7,96000.0,95700.0,95400.0,95400.0,95500.0,...,266100.0,267400,268200,268200,268000,268500,270000,272100,274600,276800
7,48113,Dallas,TX,Dallas-Fort Worth,8,0.0,0.0,0.0,0.0,0.0,...,170700.0,171400,173000,174900,176100,176700,176800,176900,177700,178700
8,36081,Queens,NY,New York,9,0.0,0.0,0.0,0.0,0.0,...,478300.0,478900,484100,494100,504400,511700,517900,525600,537200,547300
9,06065,Riverside,CA,Riverside,10,124100.0,123500.0,122900.0,122500.0,122000.0,...,332800.0,333600,334700,335700,337100,339200,341800,344300,346400,347700
10,06071,San Bernardino,CA,Riverside,11,101700.0,101800.0,101800.0,101800.0,102200.0,...,299400.0,300800,301700,302800,304400,306500,309000,310900,312600,314400
11,32003,Clark,NV,Las Vegas,12,124600.0,123900.0,123300.0,122900.0,122600.0,...,216300.0,217800,219000,220200,221900,224300,226800,229000,231400,233600
12,53033,King,WA,Seattle,13,165200.0,165000.0,165100.0,165300.0,165400.0,...,528100.0,531600,535300,541700,552300,565900,576800,581300,585100,589700
13,26163,Wayne,MI,Detroit,14,0.0,92300.0,92900.0,93700.0,90900.0,...,68400.0,69300,70300,71400,72400,73100,73200,73500,75500,78000
14,48439,Tarrant,TX,Dallas-Fort Worth,15,0.0,0.0,0.0,0.0,0.0,...,177400.0,178200,180100,182100,183500,185100,186500,187500,188600,189900
15,06085,Santa Clara,CA,San Jose,16,254400.0,254100.0,253900.0,254200.0,254800.0,...,989400.0,998300,1007800,1017200,1027500,1036100,1043500,1051700,1060800,1068000
16,12011,Broward,FL,Miami-Fort Lauderdale,17,86100.0,86200.0,86100.0,85700.0,85500.0,...,222300.0,223400,224400,225900,227900,230400,231900,233000,234900,236800
17,36061,New York,NY,New York,18,0.0,0.0,330800.0,375800.0,445200.0,...,1177600.0,1182400,1190600,1198200,1219500,1259800,1324200,1395200,1440200,1450300
18,42101,Philadelphia,PA,Philadelphia,19,50000.0,49900.0,49600.0,49400.0,49400.0,...,132600.0,133600,134500,135200,135600,136500,137000,137700,138900,140200
19,06001,Alameda,CA,San Francisco,20,190600.0,190300.0,189900.0,189800.0,190000.0,...,751800.0,758000,766200,772200,774100,774700,776500,778700,781300,783800
20,25017,Middlesex,MA,Boston,21,173000.0,173200.0,173000.0,172900.0,173200.0,...,476700.0,479400,482800,486200,489500,492900,496100,498900,500800,501500
21,36103,Suffolk,NY,New York,22,0.0,0.0,0.0,0.0,0.0,...,362500.0,365700,369700,375800,383300,386700,386400,386200,386200,385100
22,06067,Sacramento,CA,Sacramento,23,120900.0,120900.0,121000.0,121000.0,120700.0,...,319200.0,320700,322300,325100,327900,330200,332800,334900,336900,338700
23,36059,Nassau,NY,New York,24,186700.0,186900.0,186900.0,187000.0,186900.0,...,485500.0,488900,492500,495500,499200,503600,507000,507200,507300,508200
24,12099,Palm Beach,FL,Miami-Fort Lauderdale,25,98100.0,98200.0,98400.0,98500.0,98800.0,...,248800.0,249900,250500,251300,252200,253000,253400,254300,255700,256800
25,39035,Cuyahoga,OH,Cleveland,26,93700.0,94000.0,94500.0,95100.0,95600.0,...,112700.0,113800,114400,114700,115300,116500,117300,117900,118900,119900
26,12057,Hillsborough,FL,Tampa,27,74200.0,74100.0,73800.0,73400.0,72800.0,...,188500.0,190500,192500,193700,194100,194300,195200,196000,197100,198200
27,42003,Allegheny,PA,Pittsburgh,28,69300.0,69600.0,69700.0,70000.0,70300.0,...,135900.0,136500,137300,137800,138200,138700,139200,139800,140700,141600
28,26125,Oakland,MI,Detroit,29,139100.0,139800.0,140400.0,140900.0,141800.0,...,214900.0,216900,218700,220000,220800,222000,223100,223800,224800,225900
29,39049,Franklin,OH,Columbus,30,97300.0,97200.0,97300.0,97500.0,97600.0,...,147700.0,149200,150200,150800,151300,152000,152700,153200,154300,155500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,56017,Hot Springs,WY,NaN,1677,0.0,0.0,0.0,0.0,0.0,...,196400.0,196700,196700,196700,197100,197900,198500,198500,198600,198700
1677,35019,Guadalupe,NM,NaN,1678,0.0,0.0,0.0,0.0,0.0,...,132600.0,133900,134900,135800,136700,137600,138500,139000,138900,138700
1678,20119,Meade,KS,NaN,1679,0.0,0.0,0.0,0.0,0.0,...,67400.0,67600,67900,68200,68400,68900,69400,69700,70000,70100
1679,40053,Grant,OK,NaN,1680,29600.0,30400.0,31100.0,31600.0,32200.0,...,89200.0,91300,93300,95600,97800,99900,101000,101800,102500,103300
1680,20185,Stafford,KS,NaN,1681,0.0,0.0,0.0,0.0,0.0,...,57400.0,57600,57800,58000,58200,58600,58900,59200,59400,59500
1681,08091,Ouray,CO,NaN,1682,101100.0,97200.0,94100.0,91800.0,89200.0,...,358200.0,361400,364500,367100,373000,379200,380500,379500,381100,383100
1682,38069,Pierce,ND,NaN,1683,0.0,0.0,0.0,0.0,0.0,...,135700.0,135700,135300,135000,134900,135000,135000,134700,134200,134000
1683,16071,Oneida,ID,NaN,1684,0.0,0.0,0.0,0.0,0.0,...,180500.0,182200,183100,184100,185600,187700,190200,192700,195400,197000
1684,20081,Haskell,KS,NaN,1685,0.0,0.0,0.0,0.0,0.0,...,96100.0,96500,96900,97300,97800,98400,98900,99200,99600,100000
1685,27125,Red Lake,MN,NaN,1686,0.0,0.0,0.0,0.0,0.0,...,103400.0,101800,100300,99000,97600,96900,96800,96500,96600,96900
1686,20093,Kearny,KS,Garden City,1687,0.0,0.0,0.0,0.0,0.0,...,92600.0,93000,93300,93700,94300,94900,95400,95800,96000,96100
1687,16003,Adams,ID,NaN,1688,0.0,0.0,0.0,0.0,0.0,...,203000.0,202500,201700,201700,202500,203400,204700,206600,208800,210300
1688,20141,Osborne,KS,NaN,1689,0.0,0.0,0.0,0.0,0.0,...,59500.0,60000,60300,60500,60700,61100,61400,61700,61900,62000
1689,20183,Smith,KS,NaN,1690,0.0,0.0,0.0,0.0,0.0,...,60700.0,61100,61400,61700,62000,62200,62600,62900,63200,63400
1690,16061,Lewis,ID,NaN,1691,145400.0,145400.0,145400.0,145500.0,145500.0,...,164000.0,165600,166300,167200,168600,170300,172600,175100,177400,178900
1691,20019,Chautauqua,KS,NaN,1692,0.0,0.0,0.0,0.0,0.0,...,49000.0,49400,49400,49400,49800,50300,50500,50600,50900,51000
1692,30097,Sweet Grass,MT,NaN,1693,191900.0,191900.0,191900.0,192000.0,192000.0,...,206500.0,208000,209200,210300,211700,213300,214700,215600,216300,216900
1693,38029,Emmons,ND,NaN,1694,132900.0,132900.0,132900.0,133000.0,133000.0,...,138700.0,138700,138300,137900,138000,138000,137900,137600,137300,137000
1694,20207,Woodson,KS,NaN,1695,0.0,0.0,0.0,0.0,0.0,...,57500.0,57800,58000,58200,58500,58800,59100,59400,59600,59600
1695,20165,Rush,KS,NaN,1696,0.0,0.0,0.0,0.0,0.0,...,59800.0,60100,60400,60700,61000,61200,61700,61900,62200,62400
1696,20105,Lincoln,KS,NaN,1697,0.0,0.0,0.0,0.0,0.0,...,62100.0,62500,62800,62900,63300,63800,64100,64400,64600,64600
1697,20089,Jewell,KS,NaN,1698,0.0,0.0,0.0,0.0,0.0,...,58900.0,59200,59300,59400,59800,60200,60500,60700,61000,61100
1698,20047,Edwards,KS,NaN,1699,0.0,0.0,0.0,0.0,0.0,...,54500.0,54800,55000,55200,55500,55700,56100,56400,56600,56600
1699,20039,Decatur,KS,NaN,1700,0.0,0.0,0.0,0.0,0.0,...,64000.0,64400,64500,64800,65200,65500,65800,66200,66400,66600
1700,20023,Cheyenne,KS,NaN,1701,0.0,0.0,0.0,0.0,0.0,...,68500.0,69000,69300,69400,69800,70300,70700,70900,71200,71400
1701,38001,Adams,ND,NaN,1702,0.0,0.0,0.0,0.0,0.0,...,86300.0,86300,86200,86000,86000,85900,85800,85700,85600,85500
1702,49033,Rich,UT,NaN,1703,0.0,0.0,0.0,0.0,0.0,...,456800.0,461500,464100,466500,470500,475400,480200,484300,488700,491500
1703,20025,Clark,KS,NaN,1704,0.0,0.0,0.0,0.0,0.0,...,63400.0,63600,63900,64200,64500,64800,65200,65400,65700,66000
1704,20033,Comanche,KS,NaN,1705,0.0,0.0,0.0,0.0,0.0,...,55000.0,55400,55500,55700,56000,56300,56600,56900,57100,57000
1705,06003,Alpine,CA,NaN,1706,0.0,0.0,0.0,0.0,0.0,...,280200.0,283400,285100,284400,282300,282900,278300,266200,258400,256900

In [29]:
newDf['CountyCodeFIPS'].isnull().values.any()

False

In [30]:
newDf.to_csv('County_Zhvi_AllHomes_Formatted.csv')